version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/tom/dockervolumes/homarr/configs/:/app/data/configs
      - /home/tom/dockervolumes/homarr/configs/icons:/app/public/icons
      - /home/tom/dockervolumes/homarr/data:/data
    ports:
      - '7575:7575'